### ISSUE TITLE
Provide examples for the expected CSV format for bulk application deployments and bulk domain deployments

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-portal#121]
The bulk application deployment and bulk domain deployment wizards should provide a minimal example of the expected CSV file structure. One option is to have these available as placeholder values in the textarea element.

![image](https://github.com/nmaas-platform/nmaas-portal/assets/4062681/0b18b1d8-3274-4baa-b369-d31ef7c50b57)

**Comment by kbeyro** [comment]
Resolved in https://github.com/nmaas-platform/nmaas-portal/pull/123/files
