### ISSUE TITLE
Newly deployed domains do not appear in the domain switcher after bulk deployment

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-portal#122]
When using the bulk domain creation feature, newly created domains do not immediately appear in the domain switcher in the header. The admin user creating them must logout and log back in before they appear.

![Screenshot 2023-08-21 183116](https://github.com/nmaas-platform/nmaas-portal/assets/4062681/8dd6ff46-a225-4c99-8d2d-77d73feb133b)

**Comment by kbeyro** [comment]
Resolved in https://github.com/nmaas-platform/nmaas-portal/pull/123/files
