### ISSUE TITLE
Improve panels in domain-groups view

### ISSUE THREAD

**Issue by kbeyro** [nmaas-platform/nmaas-portal#164]
In `Domain-Group View` panels can grow in hight due to domains and apps list. Add option to open/close the panel tab. (similar to accordions in primeng). Solution should be visually similar to current option to avoid chaning global styling. 

In best scenario, each header panel should have icon, that would have onClick with expand option etc. 
![image](https://github.com/nmaas-platform/nmaas-portal/assets/121854496/0f68a45d-3710-4700-8238-3892fa17bdba)

**Comment by llopat** [comment]
@kbeyro some enhancements required
