### ISSUE TITLE
The access modal should open for all applications, even those that have a single access method

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-portal#210]
The access modal currently opens only for applications that have more than one access method specified (screenshot below).

![image](https://github.com/nmaas-platform/nmaas-portal/assets/4062681/e24dbdac-e7d9-4928-bf9a-4fd740768ffd)

For applications that have only a single access method, the "Access" button immediately redirects to the application's web interface. Since starting from 1.6.0 the deployment parameters are shown on this access modal, it should now be visible under all circumstances, even when a single access method is defined.

**Comment by llopat** [comment]
@pkazimierowski is it possible that under some conditions two `Access` button will appear on the `Actions` drop down menu?
We have encountered such case now.
