### ISSUE TITLE
Fix GEANT logo visibility in emails

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-portal#49]
The GEANT logo is currently not visible in emails sent from the Platform (screenshot below).
![s02](https://github.com/nmaas-platform/nmaas-portal/assets/4062681/4d21ca24-3076-4239-a486-0baa9e874654)

**Comment by llopat** [comment]
On PSNC2 and PROD instances fix needs to be applied by direct modification of the content of email template file stored on the container.

**Comment by llopat** [comment]
Fixed on PROD
