### ISSUE TITLE
App instance Members modal doesn't allow to add correct users

### ISSUE THREAD

**Issue by llopat** [nmaas-platform/nmaas-portal#77]
The selector should list those users that have roles in given domain what seems to be working correctly but users that seems to be valid are greyed out and can't be selected.

User can't be selected if he/she doesn't have a valid SSH key added but at least of them have the key, To check if which condition check is failing.

Please find the screenshot below:

![image](https://github.com/nmaas-platform/nmaas-portal/assets/21238476/6e7c0e51-6b25-43e1-b5b5-8057198cf75d)

**Comment by kbeyro** [comment]
After changing to UserViewMinimal in this view, this type does not contains SSH keys tabel. Fix in nmaas-platform should do the work

**Comment by llopat** [comment]
@kbeyro 

Adding the entire information about SSH keys to user's minimal view might not be the best idea. Maybe we could extend this view with a simple flag if SSH is added. This flag would be calculated each time a new GET request is received.
