### ISSUE TITLE
Hide extra separators in nav bar for regular users

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-portal#89]
When an admin user is logged in to NMaaS, the navbar looks like so:

![image](https://github.com/nmaas-platform/nmaas-portal/assets/4062681/7b1ed1d7-cb63-446b-8bdc-a44c51118cdd)

When a regular user who does not have permissions to send global notifications is logged in, the navbar looks like so:

![image](https://github.com/nmaas-platform/nmaas-portal/assets/4062681/da41c595-6810-4f71-86ce-10dac1cee5d2)

While the option is correctly hidden, there are extra separators which are visible. Preferably, these/this separator/s should also be hidden for regular users.

**Comment by HamzaFarooqArif** [comment]
I want to work on this issue. please assign it to me

**Comment by llopat** [comment]
@HamzaFarooqArif here you go, thank you
